# Generated by Django 4.2.7 on 2025-10-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="documents_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="payment_status",
            field=models.CharField(default="completed", max_length=20),
        ),
    ]
