# Generated by Django 4.2.7 on 2025-08-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "__first__"),
        ("forms_generation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generatedform",
            options={
                "verbose_name": "Formulario Generado",
                "verbose_name_plural": "Formularios Generados",
            },
        ),
        migrations.AddField(
            model_name="generatedform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="generatedform",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("contrato_compraventa", "Contrato de Compraventa"),
                    ("contrato_mandato", "Contrato de Mandato"),
                    ("formulario_tramite", "Formulario de Trámite"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="generatedform",
            name="generated_file",
            field=models.FileField(blank=True, null=True, upload_to="generated_forms/"),
        ),
        migrations.AlterField(
            model_name="generatedform",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="generatedform",
            table="generated_form",
        ),
        migrations.CreateModel(
            name="FormularioTramite",
            fields=[
                ("id_formulario", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_servicio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("particular", "Particular"),
                            ("publico", "Público"),
                            ("oficial", "Oficial"),
                            ("diplomatico", "Diplomático"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fecha_tramite", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_comprador",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_comprador",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tramites_comprador",
                        to="vehicles.persona",
                    ),
                ),
                (
                    "id_propietario",
                    models.ForeignKey(
                        db_column="id_propietario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tramites_propietario",
                        to="vehicles.persona",
                    ),
                ),
                (
                    "id_vehiculo",
                    models.ForeignKey(
                        db_column="id_vehiculo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulario de Trámite",
                "verbose_name_plural": "Formularios de Trámite",
                "db_table": "formulario_tramite",
            },
        ),
        migrations.CreateModel(
            name="ContratoMandato",
            fields=[
                ("id_contrato", models.AutoField(primary_key=True, serialize=False)),
                ("tramites_autorizados", models.TextField(blank=True)),
                ("organismo_transito", models.CharField(blank=True, max_length=100)),
                ("ciudad_contrato", models.CharField(blank=True, max_length=50)),
                ("fecha_contrato", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_mandante",
                    models.ForeignKey(
                        db_column="id_mandante",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandatos_mandante",
                        to="vehicles.persona",
                    ),
                ),
                (
                    "id_mandatario",
                    models.ForeignKey(
                        db_column="id_mandatario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandatos_mandatario",
                        to="vehicles.persona",
                    ),
                ),
                (
                    "id_vehiculo",
                    models.ForeignKey(
                        db_column="id_vehiculo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de Mandato",
                "verbose_name_plural": "Contratos de Mandato",
                "db_table": "contrato_mandato",
            },
        ),
        migrations.CreateModel(
            name="ContratoCompraventa",
            fields=[
                ("id_contrato", models.AutoField(primary_key=True, serialize=False)),
                (
                    "valor_venta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("valor_venta_letras", models.TextField(blank=True)),
                ("forma_pago", models.TextField(blank=True)),
                ("ciudad_contrato", models.CharField(blank=True, max_length=50)),
                ("fecha_contrato", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_comprador",
                    models.ForeignKey(
                        db_column="id_comprador",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos_comprador",
                        to="vehicles.persona",
                    ),
                ),
                (
                    "id_vehiculo",
                    models.ForeignKey(
                        db_column="id_vehiculo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehiculo",
                    ),
                ),
                (
                    "id_vendedor",
                    models.ForeignKey(
                        db_column="id_vendedor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos_vendedor",
                        to="vehicles.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de Compraventa",
                "verbose_name_plural": "Contratos de Compraventa",
                "db_table": "contrato_compraventa",
            },
        ),
    ]
