# Generated by Django 4.2.7 on 2025-09-07 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms_generation",
            "0002_alter_generatedform_options_generatedform_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariotramite",
            name="declaracion_importacion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="formulariotramite",
            name="fecha_importacion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="formulariotramite",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="formulariotramite",
            name="fecha_tramite",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="formulariotramite",
            name="tipo_servicio",
            field=models.CharField(
                choices=[
                    ("particular", "Particular"),
                    ("publico", "Público"),
                    ("oficial", "Oficial"),
                    ("diplomatico", "Diplomático"),
                ],
                default="particular",
                max_length=50,
            ),
        ),
    ]
