# Generated by Django 4.2.7 on 2025-11-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms_generation", "0003_formulariotramite_declaracion_importacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariotramite",
            name="reg_numero_chasis",
            field=models.CharField(
                blank=True, help_text="S o N", max_length=1, null=True
            ),
        ),
        migrations.AddField(
            model_name="formulariotramite",
            name="reg_numero_motor",
            field=models.CharField(
                blank=True, help_text="S o N", max_length=1, null=True
            ),
        ),
        migrations.AddField(
            model_name="formulariotramite",
            name="reg_numero_serie",
            field=models.CharField(
                blank=True, help_text="S o N", max_length=1, null=True
            ),
        ),
    ]
