# Generated by Django 4.2.7 on 2025-08-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("id_persona", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo_documento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("NIT", "NIT"),
                            ("PAS", "Pasaporte"),
                        ],
                        max_length=10,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=100)),
                ("ciudad", models.CharField(blank=True, max_length=50)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "db_table": "persona",
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                ("id_vehiculo", models.AutoField(primary_key=True, serialize=False)),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(blank=True, max_length=50)),
                ("linea", models.CharField(blank=True, max_length=50)),
                ("modelo", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=30)),
                ("numero_motor", models.CharField(blank=True, max_length=50)),
                ("numero_chasis", models.CharField(blank=True, max_length=50)),
                ("numero_vin", models.CharField(blank=True, max_length=50)),
                ("numero_serie", models.CharField(blank=True, max_length=50)),
                ("cilindraje", models.IntegerField(blank=True, null=True)),
                ("clase_vehiculo", models.CharField(blank=True, max_length=50)),
                ("carroceria", models.CharField(blank=True, max_length=50)),
                ("tipo_combustible", models.CharField(blank=True, max_length=30)),
                ("potencia_hp", models.IntegerField(blank=True, null=True)),
                ("capacidad", models.CharField(blank=True, max_length=30)),
                ("ciudad_matricula", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": "vehiculo",
            },
        ),
    ]
