# Generated by Django 4.2.7 on 2025-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_data_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="extraction_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("registration", "Registro Vehicular"),
                    ("insurance", "Seguro"),
                    ("inspection", "Inspección"),
                    ("ownership", "Tarjeta de Propiedad"),
                    ("unknown", "No identificado"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
    ]
