# Generated by Django 4.2.7 on 2025-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_add_document_methods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[("ownership", "Tarjeta de Propiedad")],
                default="unknown",
                max_length=50,
            ),
        ),
    ]
